name: Update Metrics

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly on Sundays at midnight UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Adjust to your specific version, e.g., '3.9'

    - name: Create and activate virtual environment
      run: |
        python -m venv myenv
        echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/myenv" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/myenv/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build site
      run: |
        myenv/bin/jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
